--- #YAML:1.0
name: Language-Befunge
version: 2.05
author:
  - Jerome Quelin <jquelin@cpan.org>
abstract: a Befunge-98 interpreter
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
