---
name: Language-Befunge
version: 3.00
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
abstract: a Befunge-98 interpreter
license: perl
requires:
  Storable: 0
build_requires:
  Test::More: 0
recommends:
  Test::Exception: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Language::Befunge:
    file: lib/Language/Befunge.pm
    version: 3.00
  Language::Befunge::IP:
    file: lib/Language/Befunge/IP.pm
  Language::Befunge::Interpreter:
    file: lib/Language/Befunge/Interpreter.pm
  Language::Befunge::LaheySpace:
    file: lib/Language/Befunge/LaheySpace.pm
  Language::Befunge::LaheySpace::Generic:
    file: lib/Language/Befunge/LaheySpace/Generic.pm
  Language::Befunge::Ops:
    file: lib/Language/Befunge/Ops.pm
  Language::Befunge::Ops::Befunge98:
    file: lib/Language/Befunge/Ops/Befunge98.pm
  Language::Befunge::Ops::GenericFunge98:
    file: lib/Language/Befunge/Ops/GenericFunge98.pm
  Language::Befunge::Ops::Unefunge98:
    file: lib/Language/Befunge/Ops/Unefunge98.pm
  Language::Befunge::Vector:
    file: lib/Language/Befunge/Vector.pm
  Language::Befunge::lib::FOO:
    file: lib/Language/Befunge/lib/FOO.pm
  Language::Befunge::lib::HELO:
    file: lib/Language/Befunge/lib/HELO.pm
resources:
  license: http://dev.perl.org/licenses/
