---
abstract: 'a generic funge interpreter'
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
build_requires:
  Carp: 0
  Class::XSAccessor: 0
  Config: 0
  DateTime: 0
  File::Spec::Functions: 0
  FindBin: 0
  Getopt::Long: 0
  IO::File: 0
  IO::Handle: 0
  IO::Pipe: 0
  IO::Select: 0
  List::Util: 0
  Math::BaseCalc: 0
  Math::Complex: 0
  Math::Trig: 0
  POSIX: 0
  Readonly: 0
  Storable: 0
  Test::Builder: 0
  Test::Exception: 0
  Test::More: 0
  Test::Output: 0
  Time::HiRes: 0
  UNIVERSAL::require: 0
  aliased: 0.22
  perl: 5.010
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Language-Befunge
provides:
  Language::Befunge:
    file: lib/Language/Befunge.pm
    version: 4.13
  Language::Befunge::Debug:
    file: lib/Language/Befunge/Debug.pm
  Language::Befunge::IP:
    file: lib/Language/Befunge/IP.pm
  Language::Befunge::Interpreter:
    file: lib/Language/Befunge/Interpreter.pm
  Language::Befunge::Ops:
    file: lib/Language/Befunge/Ops.pm
  Language::Befunge::Ops::Befunge98:
    file: lib/Language/Befunge/Ops/Befunge98.pm
  Language::Befunge::Ops::GenericFunge98:
    file: lib/Language/Befunge/Ops/GenericFunge98.pm
  Language::Befunge::Ops::Unefunge98:
    file: lib/Language/Befunge/Ops/Unefunge98.pm
  Language::Befunge::Storage:
    file: lib/Language/Befunge/Storage.pm
  Language::Befunge::Storage::2D::Sparse:
    file: lib/Language/Befunge/Storage/2D/Sparse.pm
  Language::Befunge::Storage::Generic::AoA:
    file: lib/Language/Befunge/Storage/Generic/AoA.pm
  Language::Befunge::Storage::Generic::Sparse:
    file: lib/Language/Befunge/Storage/Generic/Sparse.pm
  Language::Befunge::Storage::Generic::Vec:
    file: lib/Language/Befunge/Storage/Generic/Vec.pm
  Language::Befunge::Vector:
    file: lib/Language/Befunge/Vector.pm
  Language::Befunge::Wrapping:
    file: lib/Language/Befunge/Wrapping.pm
  Language::Befunge::Wrapping::LaheySpace:
    file: lib/Language/Befunge/Wrapping/LaheySpace.pm
  Language::Befunge::lib::BASE:
    file: lib/Language/Befunge/lib/BASE.pm
  Language::Befunge::lib::BOOL:
    file: lib/Language/Befunge/lib/BOOL.pm
  Language::Befunge::lib::CPLI:
    file: lib/Language/Befunge/lib/CPLI.pm
  Language::Befunge::lib::DIRF:
    file: lib/Language/Befunge/lib/DIRF.pm
  Language::Befunge::lib::EVAR:
    file: lib/Language/Befunge/lib/EVAR.pm
  Language::Befunge::lib::FILE:
    file: lib/Language/Befunge/lib/FILE.pm
  Language::Befunge::lib::FIXP:
    file: lib/Language/Befunge/lib/FIXP.pm
  Language::Befunge::lib::FOO:
    file: lib/Language/Befunge/lib/FOO.pm
  Language::Befunge::lib::HELO:
    file: lib/Language/Befunge/lib/HELO.pm
  Language::Befunge::lib::HRTI:
    file: lib/Language/Befunge/lib/HRTI.pm
  Language::Befunge::lib::MODU:
    file: lib/Language/Befunge/lib/MODU.pm
  Language::Befunge::lib::NULL:
    file: lib/Language/Befunge/lib/NULL.pm
  Language::Befunge::lib::ORTH:
    file: lib/Language/Befunge/lib/ORTH.pm
  Language::Befunge::lib::PERL:
    file: lib/Language/Befunge/lib/PERL.pm
  Language::Befunge::lib::REFC:
    file: lib/Language/Befunge/lib/REFC.pm
  Language::Befunge::lib::ROMA:
    file: lib/Language/Befunge/lib/ROMA.pm
  Language::Befunge::lib::STRN:
    file: lib/Language/Befunge/lib/STRN.pm
  Language::Befunge::lib::SUBR:
    file: lib/Language/Befunge/lib/SUBR.pm
  Language::Befunge::lib::TEST:
    file: lib/Language/Befunge/lib/TEST.pm
  Language::Befunge::lib::TIME:
    file: lib/Language/Befunge/lib/TIME.pm
recommends:
  Language::Befunge::Storage::Generic::Vec::XS: 0
  Language::Befunge::Vector::XS: v0.2.2
  Test::Pod: 0
  Test::Pod::Coverage: 0
requires:
  Carp: 0
  Class::XSAccessor: 0
  Config: 0
  DateTime: 0
  File::Spec::Functions: 0
  FindBin: 0
  Getopt::Long: 0
  IO::File: 0
  Math::BaseCalc: 0
  Math::Complex: 0
  Math::Trig: 0
  Readonly: 0
  Storable: 0
  Test::Builder: 0
  Time::HiRes: 0
  UNIVERSAL::require: 0
  aliased: 0.22
  perl: 5.010
resources:
  MailingList: http://listes.mongueurs.net/mailman/listinfo/language-befunge
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Language-Befunge
  homepage: http://search.cpan.org/dist/Language-Befunge
  license: http://dev.perl.org/licenses/
  repository: http://repo.or.cz/w/language-befunge.git
version: 4.13
